[package]
name = "nam-nih-plug"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
biquad = "0.5.0"
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }

[build-dependencies]
cc = "1.2.50"
